import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { ActionLink, WhatsAppButton } from "@/components/site/Actions";
import { Chips } from "@/components/site/Chips";
import { EditorialCard } from "@/components/site/EditorialCard";
import { HeroMotif } from "@/components/site/HeroMotif";
import { Reveal } from "@/components/site/Reveal";
import { Section, SectionIntro } from "@/components/site/Section";
import { INSTAGRAM_URL, whatsappLink } from "@/lib/brand";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "Megha Parekh · TRIKAAL — Tarot & Vastu in Mumbai" }, { name: "description", content: "When you don’t know what to do next, talk to Megha. Tarot for the question in front of you. Vastu for the space around you. Mumbai." }, { property: "og:title", content: "Megha Parekh · TRIKAAL — Tarot & Vastu in Mumbai" }, { property: "og:description", content: "Tarot for the question in front of you. Vastu for the space around you." }] }),
  component: HomePage,
});

const CONCERN_CHIPS = ["Career", "Relationships", "Marriage", "Money", "Business", "Home"];
const CONCERNS = [
  { title: "Career & Business", line: "“I’m trying, but something isn’t moving.”", cta: "Start with Tarot", intent: "tarot" as const },
  { title: "Relationships & Marriage", line: "“I need clarity on what happens next.”", cta: "Start with Tarot", intent: "tarot" as const },
  { title: "Money & Decisions", line: "“I’m unsure which move makes sense.”", cta: "Start with Tarot", intent: "tarot" as const },
  { title: "Home & Space", line: "“I want to understand my home or workspace better.”", cta: "Start with Vastu", intent: "vastu" as const },
];
const PRINCIPLES = [
  { title: "She listens first.", line: "Your concern comes before the cards or remedies." },
  { title: "She explains like a friend.", line: "You understand what she’s seeing, without the distant “guru” experience." },
  { title: "She helps you find the next step.", line: "The goal is more clarity, not more fear." },
];
const STRIP = [{ label: "Tarot notes", motif: "tarot" as const }, { label: "Vastu notes", motif: "grid" as const }, { label: "Conversations", motif: "lines" as const }];

function HomePage() {
  return <>
    <section className="surface-grain px-5 pb-16 pt-12 sm:px-8 sm:pb-24 sm:pt-20"><div className="mx-auto grid w-full max-w-6xl items-center gap-12 lg:grid-cols-[1.1fr_0.9fr]"><Reveal><p className="eyebrow">Tarot • Vastu • Personal Guidance</p><h1 className="mt-6 text-balance text-[2.6rem] leading-[1.04] sm:text-6xl lg:text-[4.1rem]">When you don’t know what to do next, talk to Megha.</h1><p className="mt-6 max-w-lg text-base leading-relaxed text-muted-foreground sm:text-lg">Tarot for the question in front of you. Vastu for the space around you.</p><Chips items={CONCERN_CHIPS} className="mt-7" /><div className="mt-9 flex flex-wrap gap-3"><WhatsAppButton size="lg">Talk to Megha</WhatsAppButton><a href="#ways" className="inline-flex min-h-12 items-center justify-center gap-2 border border-ink/25 px-8 text-[0.95rem] font-semibold tracking-wide transition-colors hover:border-oxblood hover:text-primary">Explore Tarot & Vastu</a></div><p className="mt-5 text-sm text-muted-foreground">Not sure what you need? Just tell Megha what’s been on your mind.</p></Reveal><Reveal delay={120}><HeroMotif className="mx-auto max-w-sm lg:max-w-none" /></Reveal></div></section>
    <Section><SectionIntro title="What’s bringing you here?" /><div className="mt-12 grid gap-5 sm:grid-cols-2">{CONCERNS.map((c,i)=><Reveal key={c.title} delay={i*70}><EditorialCard className="h-full justify-between"><div><h3 className="text-xl leading-snug sm:text-2xl">{c.title}</h3><p className="mt-3 font-display text-lg leading-snug text-muted-foreground">{c.line}</p></div><WhatsAppButton intent={c.intent} variant="ghost" className="mt-6 self-start">{c.cta}<ArrowRight className="h-4 w-4" aria-hidden="true" /></WhatsAppButton></EditorialCard></Reveal>)}</div><Reveal className="mt-8"><a href={whatsappLink("general")} target="_blank" rel="noopener noreferrer" className="link-underline text-sm text-primary">Mine is something else.</a></Reveal></Section>
    <Section id="ways" className="bg-ink text-parchment"><Reveal className="max-w-2xl"><h2 className="text-balance text-3xl leading-[1.12] sm:text-4xl md:text-[2.85rem]">Two ways Megha can help.</h2></Reveal><div className="mt-12 grid gap-6 lg:grid-cols-2"><Reveal><div className="flex h-full flex-col border border-parchment/20 p-7 sm:p-9"><p className="trikaal-mark">Tarot</p><h3 className="mt-5 text-2xl leading-snug sm:text-[1.9rem]">For the question you need clarity on now.</h3><Chips tone="dark" className="mt-7" items={["Career","Relationships","Marriage","Money","Business","Decisions"]} /><p className="mt-8 font-display text-3xl">₹3,000 / 60 min</p><p className="mt-2 text-sm text-parchment/70">Shorter sessions available.</p><WhatsAppButton intent="tarot" size="lg" className="mt-8 self-start bg-parchment text-ink hover:bg-mineral">Book Tarot</WhatsAppButton></div></Reveal><Reveal delay={100}><div className="flex h-full flex-col border border-parchment/20 p-7 sm:p-9"><p className="trikaal-mark">Vastu</p><h3 className="mt-5 text-2xl leading-snug sm:text-[1.9rem]">For the space you want to understand better.</h3><Chips tone="dark" className="mt-7" items={["Home","Property","Office","Workspace"]} /><p className="mt-8 font-display text-2xl leading-snug">Start with a 20-minute conversation</p><p className="mt-2 text-sm text-parchment/70">Detailed consultation: ₹12,000</p><WhatsAppButton intent="vastu" size="lg" className="mt-8 self-start bg-parchment text-ink hover:bg-mineral">Discuss Vastu</WhatsAppButton></div></Reveal></div><Reveal className="mt-10"><a href={whatsappLink("general")} target="_blank" rel="noopener noreferrer" className="link-underline text-sm text-parchment/80">Still not sure? Talk to Megha.</a></Reveal></Section>
    <Section><SectionIntro title="Why clients come back to Megha." /><div className="mt-12 grid gap-x-10 gap-y-8 md:grid-cols-3">{PRINCIPLES.map((p,i)=><Reveal key={p.title} delay={i*80} className="rule-top pt-6"><h3 className="text-xl leading-snug sm:text-2xl">{p.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground sm:text-base">{p.line}</p></Reveal>)}</div><Reveal className="mt-14"><p className="border-l-2 border-oxblood pl-5 font-display text-xl leading-snug sm:text-2xl">No fear-led predictions. No blind remedies. No need to know the service before you reach out.</p></Reveal></Section>
    <Section className="bg-muted"><div className="grid gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><Reveal><p className="eyebrow">Her story</p><h2 className="mt-4 text-balance text-3xl leading-[1.12] sm:text-4xl md:text-[2.85rem]">Vastu was the last place she thought she’d look.</h2><ActionLink to="/about" variant="outline" className="mt-9">Meet Megha</ActionLink></Reveal><div className="grid gap-6">{["Megha first came to Vastu during a difficult phase in her own life — and she was skeptical.","She tried the recommended changes, became curious about what she had experienced, and eventually studied Vastu under a MahaVastu Acharya.","Tarot entered her life through a different journey. Today, she uses both as two different ways of helping people understand what may deserve their attention next."].map((beat,i)=><Reveal key={i} delay={i*90} className="rule-top pt-5"><span className="font-display text-sm text-clay">{String(i+1).padStart(2,"0")}</span><p className="mt-2 text-base leading-relaxed sm:text-lg">{beat}</p></Reveal>)}</div></div></Section>
    <Section><div className="flex flex-wrap items-end justify-between gap-6"><SectionIntro className="max-w-md" title="From Megha’s world" /><Reveal delay={80}><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer" className="link-underline text-sm font-semibold text-primary">Follow @trikaal.megha</a></Reveal></div><div className="mt-10 grid gap-5 sm:grid-cols-3">{STRIP.map((tile,i)=><Reveal key={tile.label} delay={i*70}><a href={INSTAGRAM_URL} target="_blank" rel="noopener noreferrer" className="group block"><div className="tarot-frame aspect-[4/3] w-full overflow-hidden">{tile.motif==="grid"?<div className="grid-placeholder absolute inset-2" />:tile.motif==="tarot"?<div className="absolute inset-2 flex items-center justify-center bg-ink"><span className="font-display text-4xl text-parchment/80">◇</span></div>:<div className="absolute inset-2 flex flex-col justify-center gap-2 bg-parchment-deep px-6"><div className="h-px w-full bg-ink/15" /><div className="h-px w-4/5 bg-ink/15" /><div className="h-px w-2/3 bg-clay/50" /></div>}</div><p className="mt-3 text-sm font-medium tracking-wide text-foreground/80 group-hover:text-primary">{tile.label}</p></a></Reveal>)}</div></Section>
    <Section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-2xl text-center"><Reveal><h2 className="text-balance text-3xl leading-[1.12] sm:text-4xl md:text-[2.9rem]">You don’t need to know whether it’s Tarot or Vastu.</h2><p className="mt-5 text-base text-primary-foreground/80 sm:text-lg">Just tell Megha what’s been on your mind.</p><div className="mt-8 flex justify-center"><WhatsAppButton size="lg" className="bg-parchment text-ink hover:bg-mineral">Talk to Megha on WhatsApp</WhatsAppButton></div></Reveal></div></Section>
  </>;
}
