import { createFileRoute } from "@tanstack/react-router";
import { WhatsAppButton } from "@/components/site/Actions";
import { EditorialCard } from "@/components/site/EditorialCard";
import { FAQAccordion } from "@/components/site/FAQAccordion";
import { Reveal } from "@/components/site/Reveal";
import { Section, SectionIntro } from "@/components/site/Section";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { TRAINING_LINE } from "@/lib/brand";

export const Route = createFileRoute("/vastu")({
  head:()=>({meta:[{title:"Vastu Consultation with Megha Parekh — TRIKAAL, Mumbai"},{name:"description",content:"Vastu for homes, property, offices and workspaces in Mumbai. Start with a 20-minute conversation; detailed consultation ₹12,000."},{property:"og:title",content:"Vastu Consultation with Megha Parekh — TRIKAAL, Mumbai"},{property:"og:description",content:"Before changing your space, understand it."}],links:[{rel:"canonical",href:"/vastu"}],scripts:[{type:"application/ld+json",children:JSON.stringify({"@context":"https://schema.org","@type":"Service",name:"Vastu Consultation",serviceType:"Vastu consultation for homes and workspaces",provider:{"@type":"Person",name:"Megha Parekh"},areaServed:"Mumbai, India",offers:{"@type":"Offer",price:"12000",priceCurrency:"INR",description:"Detailed Vastu consultation."}})}]}),
  component:VastuPage,
});
const SITUATIONS=[{title:"Buying a property",line:"You want to look at it before you commit."},{title:"Existing home",line:"Something about how the home functions needs a closer look."},{title:"Office / business space",line:"Work, money or team dynamics feel stuck."},{title:"Something repeatedly feels off",line:"A pattern keeps returning in the same space."}];
const STEPS=[{title:"Start with a 20-minute conversation.",line:"Understand the concern and whether deeper Vastu work is relevant."},{title:"Detailed consultation.",line:"₹12,000 — Megha studies the concern and available layout in detail."},{title:"Go deeper only if needed.",line:"Measurements, directional mapping, remedies and follow-up can be added where relevant."}];
const FAQS=[{q:"Do I need major structural changes?",a:"Usually not. Megha begins with the least disruptive options and discusses anything larger with you first."},{q:"What information might you need from me?",a:"Typically the layout or floor plan you have, the direction the property faces, and what has been concerning you."},{q:"Can I consult before buying a property?",a:"Yes. That is one of the most common reasons people reach out."}];
function VastuPage(){return <><section className="vastu-grid px-5 pb-14 pt-14 sm:px-8 sm:pb-20 sm:pt-20"><div className="mx-auto w-full max-w-4xl"><Reveal><p className="eyebrow">Vastu</p><h1 className="mt-6 text-balance text-[2.5rem] leading-[1.05] sm:text-6xl">Before changing your space, understand it.</h1><p className="mt-6 text-sm tracking-wide text-muted-foreground sm:text-base">Home • Property • Office • Workspace</p><WhatsAppButton intent="vastu" size="lg" className="mt-9">Start with Megha</WhatsAppButton></Reveal></div></section><Section><SectionIntro title="When people come for Vastu"/><div className="mt-12 grid gap-5 sm:grid-cols-2">{SITUATIONS.map((s,i)=><Reveal key={s.title} delay={i*70}><EditorialCard className="h-full"><h3 className="text-xl leading-snug sm:text-2xl">{s.title}</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground sm:text-base">{s.line}</p></EditorialCard></Reveal>)}</div></Section><Section className="bg-ink text-parchment"><Reveal className="max-w-2xl"><h2 className="text-balance text-3xl leading-[1.12] sm:text-4xl">How it works</h2></Reveal><ol className="mt-12 grid gap-8 md:grid-cols-3">{STEPS.map((step,i)=><Reveal key={step.title} as="li" delay={i*80} className="border-t border-parchment/25 pt-6"><span className="font-display text-sm text-clay">{String(i+1).padStart(2,"0")}</span><h3 className="mt-3 font-display text-xl leading-snug sm:text-2xl">{step.title}</h3><p className="mt-3 text-sm leading-relaxed text-parchment/70">{step.line}</p></Reveal>)}</ol><Reveal className="mt-12 max-w-3xl"><Accordion type="single" collapsible><AccordionItem value="deeper" className="border-parchment/25"><AccordionTrigger className="text-left font-display text-lg hover:no-underline">What can deeper analysis involve?</AccordionTrigger><AccordionContent className="pb-6 text-sm leading-relaxed text-parchment/70">Where relevant, deeper work can include measured drawings prepared with a draftsman, mapping the space across the 16-direction grid, element-wise analysis of each zone, and specific remedies with follow-up. This is only taken up if the concern calls for it.</AccordionContent></AccordionItem></Accordion></Reveal></Section><Section className="bg-muted"><Reveal className="mx-auto max-w-3xl text-center"><p className="font-display text-xl leading-relaxed sm:text-2xl">{TRAINING_LINE}</p></Reveal></Section><Section><SectionIntro eyebrow="FAQs" title="Before you begin."/><div className="mt-10"><FAQAccordion items={FAQS}/></div></Section><Section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-2xl text-center"><Reveal><h2 className="text-balance text-3xl leading-[1.12] sm:text-4xl">Start with a conversation about your space.</h2><div className="mt-8 flex justify-center"><WhatsAppButton intent="vastu" size="lg" className="bg-parchment text-ink hover:bg-mineral">Discuss Vastu</WhatsAppButton></div></Reveal></div></Section></>}
