/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as VastuRouteImport } from './routes/vastu'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const StoriesRoute = StoriesRouteImport.update({ id: '/stories', path: '/stories', getParentRoute: () => rootRouteImport } as any)
const TarotRoute = TarotRouteImport.update({ id: '/tarot', path: '/tarot', getParentRoute: () => rootRouteImport } as any)
const VastuRoute = VastuRouteImport.update({ id: '/vastu', path: '/vastu', getParentRoute: () => rootRouteImport } as any)

export interface FileRoutesByFullPath { '/': typeof IndexRoute; '/about': typeof AboutRoute; '/contact': typeof ContactRoute; '/stories': typeof StoriesRoute; '/tarot': typeof TarotRoute; '/vastu': typeof VastuRoute }
export interface FileRoutesByTo { '/': typeof IndexRoute; '/about': typeof AboutRoute; '/contact': typeof ContactRoute; '/stories': typeof StoriesRoute; '/tarot': typeof TarotRoute; '/vastu': typeof VastuRoute }
export interface FileRoutesById { __root__: typeof rootRouteImport; '/': typeof IndexRoute; '/about': typeof AboutRoute; '/contact': typeof ContactRoute; '/stories': typeof StoriesRoute; '/tarot': typeof TarotRoute; '/vastu': typeof VastuRoute }
export interface FileRouteTypes { fileRoutesByFullPath: FileRoutesByFullPath; fullPaths: '/' | '/about' | '/contact' | '/stories' | '/tarot' | '/vastu'; fileRoutesByTo: FileRoutesByTo; to: '/' | '/about' | '/contact' | '/stories' | '/tarot' | '/vastu'; id: '__root__' | '/' | '/about' | '/contact' | '/stories' | '/tarot' | '/vastu'; fileRoutesById: FileRoutesById }
export interface RootRouteChildren { IndexRoute: typeof IndexRoute; AboutRoute: typeof AboutRoute; ContactRoute: typeof ContactRoute; StoriesRoute: typeof StoriesRoute; TarotRoute: typeof TarotRoute; VastuRoute: typeof VastuRoute }

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/about': { id: '/about'; path: '/about'; fullPath: '/about'; preLoaderRoute: typeof AboutRouteImport; parentRoute: typeof rootRouteImport }
    '/contact': { id: '/contact'; path: '/contact'; fullPath: '/contact'; preLoaderRoute: typeof ContactRouteImport; parentRoute: typeof rootRouteImport }
    '/stories': { id: '/stories'; path: '/stories'; fullPath: '/stories'; preLoaderRoute: typeof StoriesRouteImport; parentRoute: typeof rootRouteImport }
    '/tarot': { id: '/tarot'; path: '/tarot'; fullPath: '/tarot'; preLoaderRoute: typeof TarotRouteImport; parentRoute: typeof rootRouteImport }
    '/vastu': { id: '/vastu'; path: '/vastu'; fullPath: '/vastu'; preLoaderRoute: typeof VastuRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = { IndexRoute, AboutRoute, ContactRoute, StoriesRoute, TarotRoute, VastuRoute }
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
